function cur=getCurrent(env,cfg)
%GETCURRENT Build the unchanged ontology/R-GAT input from PX4 telemetry.
%   pos/vel are pad-relative; padVelocity is the deck's own world velocity, so
%   the policy can feed it forward rather than inferring a moving target.
x=env.x; rpy=mathx.quatToEulerZYX(x(7:10));
meas=struct('pos',x(1:3),'vel',x(4:6),'rpy',rpy,'omega',x(11:13), ...
    'markerProb',env.lastDiag.markerQuality, ...
    'markerDetected',env.lastDiag.markerQuality>0.1, ...
    'markerQuality',env.lastDiag.markerQuality, ...
    'padVelocity',env.lastDiag.padVelocityI, ...
    'padSpeed',env.lastDiag.padSpeed, ...
    'battery',env.lastDiag.battery);
sem=semantic.computeFeatures(x,env.lastDiag,meas,env.prevSem,cfg);
graph=semantic.buildOntologyGraph(sem,cfg);
cur=struct('meas',meas,'sem',sem,'graph',graph, ...
    'obs',sim.makeObservation(meas,sem,cfg));
end
