function reference_v28_fixture(referenceSrc, destination)
% Export deterministic primary-source equations, without training or a GUI.
addpath(referenceSrc);
c = landing2d.config.primaryConfig(fileparts(referenceSrc));
c.graphState.stateRepresentation = 'context_rgat';
p = struct('h',4,'vx',1.2,'vz',-.2,'sinTheta',sin(.03), ...
    'cosTheta',cos(.03),'pitchRate',.05,'exEstimate',.2, ...
    'relativeVxEstimate',-.12,'padVxEstimate',1.08,'padAxEstimate',.3, ...
    'positionStd',.1,'velocityStd',.2,'accelerationStd',.3, ...
    'trackInitialized',true,'detected',true,'measuredBearing',.1, ...
    'bearingValid',true,'detectionConfidence',.9,'timeSinceLastDetection',0, ...
    'predictedBearing',.2,'predictedFovMargin',c.experiment.sensor.fov/2-.2, ...
    'remainingMissionTime',35,'previousNormalizedActionX',.1, ...
    'previousNormalizedActionZ',-.2,'landingInhibited',false,'abortRequested',false);
[~,detail] = landing2d.graphstate.contextGraph(p,c);
previous = struct('ex',.25,'h',4.02,'relativeVx',-.1,'vz',-.2,'theta',.02,'pitchRate',.04);
current = struct('ex',.2,'h',4,'relativeVx',-.12,'vz',-.2,'theta',.03,'pitchRate',.05);
measurement = struct('detected',true,'bearingValid',true,'bearing',.1);
event = struct('occurred',false);
[reward,components] = landing2d.rl.computeReward(previous,current,measurement,[.2;-.1],.1,event,c);
payload = struct('reference_commit','7efcc10995557bc8435304216ad2ced70ab1da00', ...
    'packet_physical',p,'normalized_packet',landing2d.sensing.normalizePacket(p,c), ...
    'graph_X',detail.X','reward',reward,'reward_components',components);
fid = fopen(destination,'w');
assert(fid>=0,'Cannot open fixture destination');
cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(payload));
disp(payload);
end
