"""Typed configuration. Plain Python + PyYAML, no Isaac Sim import."""

from simlab.config.loader import load_config
from simlab.config.schema import (
    GATEABLE_CAMERAS,
    SCENARIO_KEYS,
    AppConfig,
    CamerasConfig,
    CameraOpticsConfig,
    ControllerConfig,
    DronesConfig,
    DroneTeamConfig,
    FrontCameraRigConfig,
    MutualOcclusionConfig,
    PersonConfig,
    PeopleConfig,
    Ros2Config,
    SceneConfig,
    ScenarioPlanEntry,
    ScenariosConfig,
    SensorConfig,
    SensorDropoutConfig,
    SatelliteCameraConfig,
    StructuralOcclusionConfig,
    TelemetryConfig,
    UGVConfig,
    WorldConfig,
)

__all__ = [
    "load_config",
    "GATEABLE_CAMERAS",
    "SCENARIO_KEYS",
    "AppConfig",
    "CamerasConfig",
    "CameraOpticsConfig",
    "ControllerConfig",
    "DronesConfig",
    "DroneTeamConfig",
    "FrontCameraRigConfig",
    "MutualOcclusionConfig",
    "PersonConfig",
    "PeopleConfig",
    "Ros2Config",
    "SceneConfig",
    "ScenarioPlanEntry",
    "ScenariosConfig",
    "SensorConfig",
    "SensorDropoutConfig",
    "SatelliteCameraConfig",
    "StructuralOcclusionConfig",
    "TelemetryConfig",
    "UGVConfig",
    "WorldConfig",
]
