function export_golden_fixture(outputPath,sourceRoot)
% EXPORT_GOLDEN_FIXTURE Export the pinned direct-policy numerical contract.
% Run from MATLAB with the ugv_landing_2d_workspace checkout at SOURCE_ROOT:
%   export_golden_fixture('results/matlab_port/matlab_golden.json','/path/to/source')
% The source checkout must be at 608225805fa447c2f8e2756e33378c32fd975797.
arguments
    outputPath (1,:) char
    sourceRoot (1,:) char
end
addpath(fullfile(sourceRoot,'src','orchestration'));
addpath(fullfile(sourceRoot,'src','simulations'));
addpath(fullfile(sourceRoot,'src','algorithms'));
c=landing2d.config.primaryConfig(sourceRoot);
% primaryConfig defaults to the plain PPO arm.  The graph fixture must select
% the proposed arm explicitly, exactly as trainEvaluate/applyMethod does.
c.graphState.stateRepresentation='context_rgat';
G=landing2d.observation.staticContext(c);
O=fixtureObservation(G.version);
v=landing2d.observation.toVector(O,G);
[flat,detail]=landing2d.graphstate.observationGraph(O,G,c);
[schema,~]=landing2d.graphstate.contextSchema('context_rgat',2,'commonObservation');
payload=struct( ...
    'schema_version','matlab-port-golden/1', ...
    'source_sha','608225805fa447c2f8e2756e33378c32fd975797', ...
    'observation_names',{landing2d.observation.vectorSchema(G).names}, ...
    'observation',v(:)', ...
    'graph_flat_matlab',flat(:)', ...
    'graph_features',detail.X, ...
    'node_names',{schema.nodeNames}, ...
    'relation_names',{schema.relationNames}, ...
    'edge_source',schema.src, ...
    'edge_target',schema.dst, ...
    'edge_relation',schema.rel, ...
    'group_matrix',schema.groupMatrix, ...
    'action_max',[c.axMax,c.azMax], ...
    'training',struct('updates',c.rl.ppoIterations, ...
        'evaluate_every',c.rl.evaluateEvery,'policy_lr',c.rl.policyLearnRate, ...
        'value_lr',c.rl.valueLearnRate,'encoder_lr',c.graphState.encoderLearnRate, ...
        'entropy',c.rl.entropyWeight,'initial_log_std',c.rl.initialLogStd));
parent=fileparts(outputPath);
if ~isempty(parent) && ~exist(parent,'dir'), mkdir(parent); end
fid=fopen(outputPath,'w');
cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s',jsonencode(payload,'PrettyPrint',true));
end

function O=fixtureObservation(version)
ugv=struct('positionXZ',[7.0;0.0],'velocityXZ',[1.5;0.0], ...
    'visionUpdated',true,'visionAge',0.2,'estimateInitialized',true, ...
    'visionStamp',3.8);
drone=struct('positionXZ',[5.0;4.6],'velocityXZ',[0.5;-0.3], ...
    'pitchSinCos',[sin(0.1);cos(0.1)],'pitchRate',0.2, ...
    'navigationValid',true,'navigationAge',0.05,'navigationStamp',3.95);
history=struct('ugvPositionXZ',[6.9;0],'ugvVelocityXZ',[1.4;0], ...
    'dronePositionXZ',[4.95;4.63],'droneVelocityXZ',[0.5;-0.3], ...
    'ugvInitialized',true,'valid',true);
O=struct('schemaVersion',version,'decisionTime',4.0,'ugv',ugv, ...
    'drone',drone,'history',history);
end
